language: ruby
rvm:
  - 2.1

branches:
  only:
    - gh-pages

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - set -e
  - bundle exec jekyll build --drafts
  - bundle exec htmlproof ./_site

notifications:
  email: true
