# Site wide configuration

title: Writing papers and thesis using LaTeX
locale: en_GB
description: Introduction to LaTeX for beginners
#logo: site-logo.png
search: true
url: https://kks32.github.io/latex-paper-thesis
#url: 


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Krishna Kumar
#  avatar: bio-photo.jpg
  email: kks32@cam.ac.uk
#  disqus-shortname:
#  twitter: #username
#  facebook: #username
  github: kks32
  github_project: https://github.com/kks32/latex-paper-thesis
#  stackexchange: #http://stackoverflow.com/users/123456/username
#  linkedin: #username
#  instagram: #username
#  flickr: #username
#  tumblr: #username
#  google:
#    plus: #username
#    analytics:
#    verify:
#    ad-client:
#    ad-slot: 
#  bing-verify: